### ISSUE TITLE
Supporing JDK 20 with GraalVM >22

### ISSUE THREAD

**Issue by tusharmath** [sbt/sbt-github-actions#157]
Then naming convention has changed in the latest version of graalvm. Because of this change we aren't able to upgrade to the latest version of Graal as it introduces a download error.

**More Info**
https://github.com/graalvm/setup-graalvm#migrating-from-graalvm-223-or-earlier-to-the-new-graalvm-for-jdk-17-and-later

The new [GraalVM for JDK 17 and JDK 20 release](https://medium.com/graalvm/a-new-graalvm-release-and-new-free-license-4aab483692f5) aligns the GraalVM version scheme with OpenJDK. As a result, this action no longer requires the version option to select a specific GraalVM version. At the same time, it introduces a new distribution option to select a specific GraalVM distribution (graalvm, graalvm-community, or mandrel). Therefore, to migrate your workflow to use the latest GraalVM release, replace the version with the distribution option in the workflow yml config, for example:

```yml
# ...
- uses: graalvm/setup-graalvm@v1
  with:
    java-version: '17'
    version: '22.3.2' # Old 'version' option for the GraalVM version
    # ...
```
can be replaced with:

```yml
# ...
- uses: graalvm/setup-graalvm@v1
  with:
    java-version: '17.0.7' # for a specific JDK 17; or '17' for the latest JDK 17
    distribution: 'graalvm' # New 'distribution' option
    # ...
```
